<a href="https://colab.research.google.com/github/kunaaaaaal-cmd/ml-internship-starter/blob/main/work/notebook/w01_research_question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 Research Question

## Selected Lane

CTR / Engagement Opportunity Scoring

## Search Question

Which webpages have the greatest opportunity to improve their click-through rate (CTR), and which page characteristics are associated with low CTR despite receiving many impressions?

## Unit of Analysis

Each webpage in the dataset.

## Expected Output

A ranked list of webpages with the highest opportunity to improve CTR and the factors contributing to their performance.

## Action Someone Could Take

SEO specialists and content writers can prioritize webpages with high impressions but low CTR. They can improve page titles, meta descriptions, and content to increase user engagement and clicks.

## Cost of a Wrong Recommendation

If the recommendations are inaccurate, teams may spend time optimizing pages with little improvement potential while overlooking pages that could significantly increase website traffic.

## Why Machine Learning Helps

Machine learning can analyze multiple page-level features simultaneously and identify hidden patterns that are difficult to detect manually. It helps prioritize webpages with the highest potential for improving CTR.

In [18]:
!pwd
!ls

/content/ml-internship-starter
AGENTS.md    docs	outputs		  SETUP.md		       work
CLAUDE.md    GUIDE.md	README.md	  skills
data	     LICENSE	requirements.txt  submission
DATA_USE.md  notebooks	scripts		  w01_research_question.ipynb

In [19]:
!git clone https://github.com/kunaaaaaal-cmd/ml-internship-starter.git

Cloning into 'ml-internship-starter'...
remote: Enumerating objects: 127, done.
remote: Counting objects: 100% (127/127), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 127 (delta 39), reused 96 (delta 28), pack-reused 0 (from 0)
Receiving objects: 100% (127/127), 1.84 MiB | 9.49 MiB/s, done.
Resolving deltas: 100% (39/39), done.

In [20]:
%cd ml-internship-starter

/content/ml-internship-starter/ml-internship-starter

In [21]:
!ls

AGENTS.md    docs	outputs		  SETUP.md		       work
CLAUDE.md    GUIDE.md	README.md	  skills
data	     LICENSE	requirements.txt  submission
DATA_USE.md  notebooks	scripts		  w01_research_question.ipynb

In [22]:
!find data -type f

data/raw/content_refresh_anonymized.csv

In [23]:
!find . -type f | grep -E '\.(csv|parquet)$'

./data/raw/content_refresh_anonymized.csv
./outputs/refresh_queue_sample.csv

In [24]:
import pandas as pd

# Load the starter dataset
df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

# Display basic information
print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

df.head()

Dataset Shape: (30000, 44)

Columns:
['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [25]:
for col in df.columns:
    print(col)

content_id
client_id
search_volume
competition
competition_level
cpc
content_type
main_intent
word_count
char_count
provider_used
model_used
impressions_90d
clicks_90d
pageviews_90d
sessions_90d
users_90d
engaged_sessions_90d
ai_sessions_90d
scroll_events_90d
days_with_impressions
days_with_sessions
impressions_last_30d
clicks_last_30d
sessions_last_30d
impressions_prev_30d
clicks_prev_30d
sessions_prev_30d
content_age_days
age_tier
age_tier_order
days_since_last_update
freshness_tier
word_count_tier
char_count_tier
ctr
avg_position
engagement_rate
scroll_rate
ai_traffic_pct
impression_tier
position_tier
trend_direction
trend_pct

In [26]:
import pandas as pd

# Load the dataset
df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [27]:
# Supporting statistics for my chosen lane

print("Total Pages:", len(df))
print("Average CTR:", round(df["ctr"].mean(), 4))
print("Average Impressions (90d):", round(df["impressions_90d"].mean(), 2))
print("Average Position:", round(df["avg_position"].mean(), 2))

print("\nTrend Direction Distribution:")
print(df["trend_direction"].value_counts())

Total Pages: 30000
Average CTR: 0.5107
Average Impressions (90d): 5200.37
Average Position: 16.34

Trend Direction Distribution:
trend_direction
down      16262
stable     5962
up         4388
new        2236
flat       1152
Name: count, dtype: int64

## Supporting Evidence

The starter dataset contains **30,000 webpages** with **44 features**, providing sufficient data for CTR analysis.

The calculated statistics show the average CTR, average impressions over the last 90 days, and average search position. The trend direction distribution further demonstrates that webpages perform differently over time, making it possible to identify pages with high improvement potential.

These observations support my decision to choose the **CTR / Engagement Opportunity Scoring** lane for the next seven weeks because machine learning can help prioritize which pages should be optimized first.